#!/usr/bin/env bash
input="$1"

# Calculate and print the video_id of the video that has the most number of occurrences in the data.
gawk -F',' '{count[$1]++} END {for (id in count) {print id, count[id]}}' "$input" | sort -k2 -nr | head -1 | gawk '{print "Most frequent video, ID: " $1}'

# Calculate and print the mean (2 places after the decimal) number of views
gawk -F',' 'NR>1 {sum_views+=$3; count++} END {
    if (count > 0) printf ("Mean number of views: %.2f\n", sum_views/count) 
    else print "No data to calculate mean."
    }' "$input"
# Calculate and print the video_id of the video with the maximum number of dislikes
gawk -F',' 'NR>1 {if ($5 > max) {max=$5; id=$1}} END {print "Max dislikes video, ID: " id}' "$input"


