#!/usr/bin/env bash

# Added error handling	
# 1) No input file specified
if [ $# -eq 0 ]; then
    echo "ERROR: No input CSV file provided"
    exit 1
fi

input="$1"

# 2) Input file not found in the current directory
if [ ! -f "$input" ]; then
    echo "ERROR: Input file not found in the current directory"
    exit 1
fi

# 3) Input file is not a CSV file
if [[ "$input" != *.csv ]]; then
    echo "ERROR: Input file expected in a CSV format"
    exit 1
fi

# 4) Input file is empty
if [ ! -s "$input" ]; then
    echo "ERROR: Empty file provided"
    exit 1
fi

# 5) Input CSV file has incorrect number of columns (expected 7)
cols=$(head -1 "$input" | gawk -F',' '{print NF}')
if [ "$cols" -ne 7 ]; then
    echo "ERROR: Expected 7 columns in the input"
    exit 1
fi

# Delete the column named ratings_disabled
cut -d',' -f1-6 "$input" > data_cleaned.csv

# Delete those rows that contain any empty fields
tmp=$(mktemp)
gawk -F',' 'NF==6 && ($0 !~ /^,/ && $0 !~ /,,/ && $0 !~ /,$/) {print}' data_cleaned.csv > "$tmp"
mv "$tmp" data_cleaned.csv

# Delete any duplicate rows from your data
tmp=$(mktemp)
gawk '!seen[$0]++' data_cleaned.csv > "$tmp"
mv "$tmp" data_cleaned.csv

#Delete rows that do not contain a video_id
tmp=$(mktemp)
gawk -F',' '$1 != "" {print}' data_cleaned.csv > "$tmp"
mv "$tmp" data_cleaned.csv

#Delete rows which contain zero number of likes or dislikes
tmp=$(mktemp)
gawk -F',' '$5 != "0" && $6 != "0" {print}' data_cleaned.csv > "$tmp"
mv "$tmp" data_cleaned.csv  

